### ISSUE TITLE
Some typos / errors

### ISSUE THREAD

**Issue by tomersagi** [sonatype/maven-example-en#10]
Hi,
Great book! I found a couple of typos/errors you might want to correct:
In Section 3.5.2 (Maven Lifecycle), the third paragraph ends abruptly:
>These goals are executed as Maven steps through the phases preceding package in the

In Section 4.3, reader is directed to choose archtype 16, which is not a simple archtype, and is not deterministic. I suggest using the same instructions issued in section 3.5, assuming you meant the simple project archtype.

Further down in Section 4.3, the reader is instructed to add a dependency to the maven-compiler-plugin. But the code lacks a version tag which causes a warning in the subsequent invocation of mvn install. I suggest you supply some version or instruct otherwise. 

In Section 5.4, the jetty plugin is shown as the only plugin within the build tag, while it should be added to the existing build tag that already has the maven-compiler-plugin configuration info.

In Section 6.3, the second sentence ends abruptly: 
>"The first submodule we’re going to look at is the simple-weather submodule. This submodule contains all"

In section 6.5 the build instructions do not match the project structure in the example. There is an additional level of POM above simple-parent and if you don't run mvn clean install from ch-multi folder, you get an error when trying to run jetty:run from the simple-webapp folder. 

Thanks again for the effort, 
Tomer

**Comment by mosabua** [comment]
This should all be fixed now.
