### ISSUE TITLE
"JDK" sentence fragment at start of Chapter 2

### ISSUE THREAD

**Issue by apjanke** [sonatype/maven-example-en#11]
Chapter 2 (Installing Maven) starts out with a sentence fragment, like this:

    Java Development Kit (JDK). If you are just interested in installation, you can...

I don't know what that first sentence about the JDK is supposed to be, so I can't suggest a PR to fix it.

**Comment by mosabua** [comment]
Thanks for noticing that. I am going to push a fix live in a bit.
