### ISSUE TITLE
Windows installation instructions half-create new environment variable

### ISSUE THREAD

**Issue by apjanke** [sonatype/maven-example-en#13]
In section 2.3.2 where it gives instructions for installing Maven on Windows, it instructs the user to create a new environment variable with the step "Click on New (the lower in the System variables section)". But it doesn't tell you what name or value to give this new variable, and it just proceeds to discuss modifying the `Path` variable.

Perhaps this step is a holdover from Maven 2.x where you needed to create an `M2_HOME` environment variable during the installation process, and can just be removed?

The section also uses the plural form "environment variables", even though only one, `Path`, is being altered. Maybe another holdover from `M2_HOME`?

Also, in this set of steps, the name "Path" is not typeset as code, like the rest of the environment variable names are.

Then, section 2.4 says to make sure `M2_HOME` is properly set if `mvn` isn't working. But I don't think that's required with the current 3.x Maven line. (Though an incorrect `M2_HOME` will still break things.) Don't know if you'd want to pull or clarify that.

**Comment by mosabua** [comment]
Let me fix that. You are correct btw. These are left overs from the change.
