### ISSUE TITLE
Spurious a2x "--destination-dir" warning in build 

### ISSUE THREAD

**Issue by apjanke** [sonatype/maven-example-en#15]
When building the book using AsciiDoc 8.6.9, the `build.sh` script issues a warning about `a2x`'s `--destination-dir` option not working for PDFs.

```
$ ./build.sh
Building PDF
a2x: WARNING: --destination-dir option is only applicable to HTML based outputs
done
Building Mutli Page HTML
done
```

Looks like this warning is spurious, and due to a bug introduced in AsciiDoc 8.6.9. (See asciidoc/asciidoc#44). The warning can be ignored, and will be fixed in an upcoming release of AsciiDoc.

A way to suppress it in this build script would be nice, but I don't see a way of doing that besides some clumsy output munging.

**Comment by mosabua** [comment]
This is an asciidoc bug. Once I merge the pull requests this will be gone so I am going to close this separate issue here.
