### ISSUE TITLE
Capitalize "Simple Weather project"?

### ISSUE THREAD

**Issue by apjanke** [sonatype/maven-example-en#18]
In chapter 4, the example project is "the simple weather project", which is referred to as such several times. Is "simple weather" just a description, or is it the actual name of the project? If it's the name, should it be capitalized as "Simple Weather" instead? There's one point in section 4.13 where it's capitalized that way, but everywhere else it's lower case. To me it seems like this should be the proper name of the project, and it reads a little oddly in lower case.

Similarly, styling Yahoo as "Yahoo!" with the exclamation mark everywhere makes things a bit hard to scan for me. I've seen other places (Google, WSJ, NYT) drop the "!". Maybe this book should as well?

**Comment by mosabua** [comment]
https://github.com/sonatype/maven-example-en/commit/bfec5bd24d92d2236f9a891d7e7ab930d6e6f7c1
