### ISSUE TITLE
PDF not building on OS X

### ISSUE THREAD

**Issue by dc55028** [sonatype/maven-example-en#39]
I have installed the prerequisites on OS X v10.11.2:
- asciidoc v8.6.9 (with homebrew)
- docbook v5.0 (with homebrew)
- docbook-xsl v1.78.1 (with homebrew)
- dblatex v0.3.7 (with pip)
and added the variable XML_CATALOG_FILES to .bashrc

The html, chunked and epub formats are building fine, but the PDF does not.
The last command run by `./build.sh -v -f pdf` is this one:
```
xsltproc -o book-mvnex.rtex --xinclude --xincludestyle --param current.dir '/Users/dom/sources/maven-example-en/target' --param listings.xml '/var/folders/3c/7yhz9w_n449dbhzqp3v6hb9c0000gn/T/tmpfttOdr/listings.xml' /private/var/folders/3c/7yhz9w_n449dbhzqp3v6hb9c0000gn/T/tmpfttOdr/custom.xsl /Users/dom/sources/maven-example-en/target/book-mvnex.xml
XSLT stylesheets DocBook - LaTeX 2e (0.3.7)
===================================================
Build book-mvnex.pdf
built-in module pdftex registered
no support found for ifxetex
no support found for fontspec
no support found for xltxtra
no support found for fontenc
no support found for inputenc
no support found for fancybox
built-in module makeidx registered
no support found for custom-docbook
building additional files...
checking if compiling is necessary...
the output file doesn't exist
pdflatex -interaction=batchmode book-mvnex.tex
Unexpected error occured
Error: [Errno 2] No such file or directory
```
any idea ?

**Comment by mosabua** [comment]
Switch the a2x execution in the build.sh file to verbose with-v and see what that says..

**Comment by dc55028** [comment]
it was already in verbose mode... and --debug or --dump don't help either.

after trying further the different commands run by dblatex, the "pdflatex" command was not in the path or not linked correctly in a bin directory of the path.

linking it in /usr/local/bin fixes the problem.
I'll try to find what wasn't correctly installed but this issue's closed.
