### ISSUE TITLE
Links to download examples don't work

### ISSUE THREAD

**Issue by burgeris** [sonatype/maven-example-en#43]
Hi, I found that links to examples doesn't work anymore, for example, in 6.1.1 chapter link to http://www.sonatype.com/books/mvnex-book/mvnex-examples.zip redirects to http://books.sonatype.com/mvnex-book/reference/index.html.

**Comment by cyberjoac** [comment]
+1

**Comment by tjago** [comment]
the link has changed, because all content was transfered to subdomain books, the valid link is as follows:

http://books.sonatype.com/mvnex-book/mvnex-examples.zip

**Comment by mosabua** [comment]
I recently fixed that and deployed the new version. If you find anything where its still wrong please let me know by reopening here or a new issue.
