### ISSUE TITLE
8.5 dependencies better explanation

### ISSUE THREAD

**Issue by burgeris** [sonatype/maven-example-en#45]
I don't quite understand this paragraph. How can transitive dependencies still be there if the dependency requiring them is removed? Let's say an example with hibernate - if we remove it, BeanUtils won't be there, so why wouldn't it compile?

> On larger projects, additional dependencies often tend to creep into a POM as the number of dependencies
grow. As dependencies change, you are often left with dependencies that are not being used, and just as
often, you may forget to declare explicit dependencies for libraries you require. Because Maven 2.x
includes transitive dependencies in the compile scope, your project may compile properly but fail to run
in production. Consider a case where a project uses classes from a widely used project such as Jakarta
Commons BeanUtils. Instead of declaring an explicit dependency on BeanUtils, your project simply
relies on a project like Hibernate that references BeanUtils as a transitive dependency. Your project may
compile successfully and run just fine, but if you upgrade to a new version of Hibernate that doesn’t
depend on BeanUtils, you’ll start to get compile and runtime errors, and it won’t be immediately obvious
why your project stopped compiling. Also, because you haven’t explicitly listed a dependency version,
Maven cannot resolve any version conflicts that may arise.

**Comment by Xassassin** [comment]
I think you are misreading. BeanUtils is currently a dependency of Hibernate. If your project uses classes from Hibernate and from beanutils, but you only declared Hibernate as a dependency for your project today; it will compile and work.

If tomorrow you stop using hibernate classes and remove the hibernate dependency, you project will not compile, as you do not have the BeanUtils declared as a dependency.

Also, if tomorrow hibernate decides for its next version to remove the BeanUtils dependency, and you upgrade to that version, you no longer have BeanUtils as a (transitive) dependency and you project will not compile.

**Comment by burgeris** [comment]
Yeah, I understood that a little bit later. I guess I found it confusing because why would you use classes from transitive dependencies. But if you do use them, there won't be any problem to add a line of that dependency to your pom if it doesn't compile (and the IDE will show the failed imports anyway).
